### PR TITLE
add new feature and compatibility

### PR DESCRIPTION
**Pull request by syrinka**
- remove some duplicated files
- new feature: only awaken pawn will lose XP
- compatible with Vanilla Skills Expanded

### CODE REVIEW

**Comment by syrinka** [comment]
There's a minor bug on retention feature. It need to record the last tick `SkillRecord.Learn` is called, since I use `ConditionalWeakTable` to store the ticks data, I have no idea how to save/load it correcly, the retention effect will be lost between save/load

**Comment by Ratysz** [comment]
These are not "duplicated files", they are very much necessary for backwards compatibility and licensing. Yes, it matters.

I'm not interested in adding and maintaining the new features as they appear in this PR either, but I will open an issue for them in case I ever get to it. Making a PR to close that issue, even if absolutely perfect and exactly as I would've done it myself, would not expedite that process, sorry.

**Comment by syrinka** [comment]
> These are not "duplicated files", they are very much necessary for backwards compatibility and licensing. Yes, it matters.
> 
> I'm not interested in adding and maintaining the new features as they appear in this PR either, but I will open an issue for them in case I ever get to it. Making a PR to close that issue, even if absolutely perfect and exactly as I would've done it myself, would not expedite that process, sorry.

Well yeah I understand. And since you're not gonna update in the near future, would you mind I publish my modified version to workshop? I'll keep the license and link to yours.

**Comment by Ratysz** [comment]
I don't mind, go ahead. I would request, however, that you make it clear that your version is a fork and not a successor.

**Pull request closed without merging**
